% cat12_test
% test matlab code to make sure it works before compiling


cat12_long(...
    't1_1_nii','../../INPUTS/t1_1.nii', ...
    't1_2_nii','../../INPUTS/t1_2.nii', ...
    'longmodel','1', ...
    'nproc','18',...
    'gcutstr','2',...
    'vox','1',...
    'bb','12',...
    'fwhm','4',...
    'out_dir','../../OUTPUTS' ...
);

